#!/usr/bin/env torch-lua

print '==> building lua and 3rd party packages as static libs'
os.execute[[
   unset CC
   unset CXX
   rm -f build/CMakeCache.txt
   mkdir -p build
   cd build
   cmake ..
   make
]]

print '==> exporting libs + headers'
os.execute[[
   mkdir -p framework/lib
   mkdir -p framework/include

   cp build/exe/lua/libtorch-lua-static.a framework/lib/
   cp build/3rdparty/nn/libnn.a framework/lib/
   cp build/lib/luaT/libluaT.a framework/lib/
   cp build/lib/TH/libTH.a framework/lib/
   cp build/pkg/torch/libtorch.a framework/lib/
   cp build/3rdparty/image/libimage.a framework/lib/
   cp build/3rdparty/nnx/libnnx.a framework/lib/

   path=`which torch-lua`
   path=`dirname $path`
   cp -r $path/../include/torch/* framework/include/
]]

print '==> exporting Lua sources'
os.execute[[
   mkdir -p framework/lua/torch
   cp -r pkg/torch/*.lua framework/lua/torch/

   mkdir -p framework/lua/dok
   cp -r pkg/dok/*.lua framework/lua/dok/

   mkdir -p framework/lua/nn
   cp -r 3rdparty/nn/*.lua framework/lua/nn/

   mkdir -p framework/lua/nnx
   cp -r 3rdparty/nnx/*.lua framework/lua/nnx/

   mkdir -p framework/lua/image
   cp -r 3rdparty/image/*.lua framework/lua/image/
]]

print '==> exported complete framework in framework/'
print '    just drag the whole dir into your iOS project'

