#!/usr/bin/env torch-lua

print '==> building lua and 3rd party packages as static libs'
os.execute[[
   rm -f build/CMakeCache.txt
   mkdir -p build
   cd build
   cmake ..
   make
]]

print '==> exporting libs + headers'
os.execute[[
   mkdir -p framework/lib
   mkdir -p framework/include

   cp build/exe/lua/libtorch-lua-static.a framework/lib/
   cp build/extra/nn/libnn.a framework/lib/
   cp build/lib/luaT/libluaT.a framework/lib/
   cp build/lib/TH/libTH.a framework/lib/
   cp build/pkg/torch/libtorch.a framework/lib/
   cp build/3rdparty/image/libimage.a framework/lib/
   cp build/3rdparty/nnx/liblbfgs.a framework/lib/
   cp build/3rdparty/nnx/libnnx.a framework/lib/

   path=`which torch-lua`
   path=`dirname $path`
   cp -r $path/../include/torch/* framework/include/
]]

print '==> exporting Lua sources'
os.execute[[
   mkdir -p framework/lua

   cp -r pkg/torch/*.lua framework/lua/
   mv framework/lua/init.lua framework/lua/torch.lua

   cp -r pkg/dok/*.lua framework/lua/
   mv framework/lua/init.lua framework/lua/dok.lua

   cp -r extra/nn/*.lua framework/lua/
   mv framework/lua/init.lua framework/lua/nn.lua

   cp -r 3rdparty/nnx/*.lua framework/lua/
   mv framework/lua/init.lua framework/lua/nnx.lua

   cp -r 3rdparty/image/*.lua framework/lua/
   mv framework/lua/init.lua framework/lua/image.lua
]]

print '==> exported complete framework in framework/'
print '    just drag the whole dir into your iOS project'

